services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: '${DEV_POSTGRES_DB:-savings}'
      POSTGRES_USER: '${DEV_POSTGRES_USER:-savings}'
      POSTGRES_PASSWORD: '${DEV_POSTGRES_PASSWORD:-savings}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DEV_POSTGRES_DB:-savings}", "-U", "${DEV_POSTGRES_USER:-savings}" ]
      retries: 3
      timeout: 5s
  kc-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: '${KC_POSTGRES_PASSWORD:-savings}'
      POSTGRES_USER: '${KC_POSTGRES_USER:-savings}'
      POSTGRES_DB: '${KC_POSTGRES_DB:-savings}'
    volumes:
      - kc-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${KC_POSTGRES_DB:-fm}", "-U", "${KC_POSTGRES_USER:-fm}" ]
      retries: 3
      timeout: 5s
  keycloak:
      image: quay.io/keycloak/keycloak:21.0.1
      restart: unless-stopped
      environment:
        KC_HOSTNAME: localhost
        KC_HOSTNAME_PORT: 8081
        KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
        KC_DB: postgres
        KC_DB_URL: 'jdbc:postgresql://kc-db:5432/${KC_POSTGRES_DB:-savings}?characterEncoding=UTF-8'
        KC_DB_USERNAME: '${KC_POSTGRES_USER:-savings}'
        KC_DB_PASSWORD: '${KC_POSTGRES_USER:-savings}'
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: "true"
        KC_HEALTH_ENABLED: "true"
        KC_LOG_LEVEL: info
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8081/health/ready" ]
        interval: 15s
        timeout: 2s
        retries: 15
      links:
        - kc-db
      depends_on:
        - kc-db
      ports:
        - '8081:8080'
        - '8443:8443'
      command: start-dev
  app:
    image: savings_categorization:latest
    restart: unless-stopped
    ports:
      - "8085:8080"
    links:
      - keycloak
      - postgres
    environment:
      POSTGRES_DB_URL: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_SCHEMA: savings
      POSTGRES_DB_USERNAME: savings
      POSTGRES_DB_PASSWORD: savings
      OIDC_ISSUER_HOST: http://localhost:8081
      OIDC_JWK_HOST: http://keycloak:8080
      OIDC_REALM: savings-categorization
      FRONTEND_OIDC_AUTHORITY: http://localhost:8081/realms/savings-categorization
      FRONTEND_CLIENT_ID: react-client
      FRONTEND_REDIRECT_URI: http://localhost:5173/

volumes:
  postgres-data:
  kc-db-data: